export const PROPERTY_DATABASE_CONSTANTS = {
  UI: {
    SKELETON_ROWS_COUNT: 5,
  },
  COLUMN_TYPES: {
    TEXT: 'text',
    NUMBER: 'number',
    DATE: 'date',
    SELECT: 'select',
    BOOLEAN: 'boolean',
    TEXTAREA: 'textarea',
  },
  DEFAULT_VALUES: {
    TEXT: '',
    NUMBER: 0,
    DATE: () => new Date(),
    SELECT: 'option1',
    BOOLEAN: false,
  },
  SELECT_OPTIONS: [
    { value: 'option1', label: 'Опция 1' },
    { value: 'option2', label: 'Опция 2' },
    { value: 'option3', label: 'Опция 3' },
  ],
  OCCUPANCY_STATUS: {
    AVAILABLE: 'свободна',
    OCCUPIED: 'занята',
  },
  BADGE_VARIANTS: {
    AVAILABLE: 'bg-green-50 text-green-700 hover:bg-green-50',
    OCCUPIED: 'bg-orange-50 text-orange-700 hover:bg-orange-50',
  },
  MESSAGES: {
    LOADING: 'Loading properties...',
    ERROR: 'Error:',
    NOT_FOUND: 'Property not found',
    PROPERTY_DATABASE: 'Обзор Недвижимости',
    FOUND: 'Найдено:',
    AVAILABLE: 'Свободна',
    OCCUPIED: 'Занята',
    SHOW_MAIN: 'Показать основные',
    HIDDEN: 'Скрытые',
    ADD_PROPERTY: 'Добавить Недвижимость',
    RETURN_TO_MAIN: 'Вернуть в основные',
    HIDE_SELECTED: 'Скрыть выбранные',
    DELETE_SELECTED: 'Удалить выбранные',
    SELECT_ALL: 'Выбрать все',
    SELECT_ROW: 'Выбрать строку',
    APARTMENT_NUMBER: 'Номер Квартиры',
    LOCATION: 'Расположение',
    ROOMS: 'Комнаты',
    READINESS_STATUS: 'Готовность',
    PROPERTY_TYPE: 'Тип',
    OCCUPANCY_STATUS: 'Статус',
    URGENT_MATTER: 'Срочные Вопросы',
    CREATED: 'Создано',
    UPDATED: 'Обновлено',
    ACTIONS: 'Действия',
    DELETE_RECORD: 'Удалить запись?',
    DELETE_DESCRIPTION: 'Действие необратимо. Запись будет удалена.',
    CANCEL: 'Отмена',
    DELETE: 'Удалить',
    DELETE_COLUMN: 'Удалить колонку',
    DELETE_COLUMN_CONFIRM: 'Удалить колонку?',
    DELETE_COLUMN_DESCRIPTION: 'Действие необратимо. Колонка будет удалена из всех записей.',
    ADD_COLUMN: 'Добавить колонку',
    SHOW_COLUMNS: 'Показать колонки',
  },
} as const;

export const DEBOUNCE_DELAY = 300;
export const MAX_RETRY_ATTEMPTS = 3;
