export const TENANT_DATABASE_CONSTANTS = {
  STORAGE_KEYS: {
    CUSTOM_COLUMNS: 'tenant-custom-columns',
  },
  UI: {
    SKELETON_ROWS_COUNT: 5,
    DATE_FORMATS: {
      DD_MM: 5,
      DD_MM_YYYY: 10,
    },
  },
  COLUMN_TYPES: {
    TEXT: 'text',
    NUMBER: 'number',
    DATE: 'date',
    SELECT: 'select',
    BOOLEAN: 'boolean',
    TEXTAREA: 'textarea',
    APARTMENT: 'apartment',
    STATUS: 'status',
  },
  DEFAULT_VALUES: {
    TEXT: '',
    NUMBER: 0,
    DATE: () => new Date(),
    SELECT: 'option1',
    BOOLEAN: false,
  },
  SELECT_OPTIONS: [
    { value: 'option1', label: 'Опция 1' },
    { value: 'option2', label: 'Опция 2' },
    { value: 'option3', label: 'Опция 3' },
  ],
  TENANT_STATUS: {
    CURRENT: 'current',
    PAST: 'past',
    FUTURE: 'future',
    UPCOMING: 'upcoming',
  },
  BADGE_VARIANTS: {
    CURRENT: 'bg-green-100 text-green-800 hover:bg-green-100',
    UPCOMING: 'bg-orange-100 text-orange-800 hover:bg-orange-100',
    FUTURE: 'bg-blue-100 text-blue-800 hover:bg-blue-100',
    PAST: 'bg-gray-100 text-gray-800 hover:bg-gray-100',
  },
  MESSAGES: {
    LOADING: 'Loading user profile...',
    ERROR: 'Error:',
    NOT_FOUND: 'User not found',
    FAILED_TO_PARSE: 'Не удалось разобрать сохраненные пользовательские колонки:',
    TENANT_DATABASE: 'База Данных Арендаторов',
    FOUND: 'Найдено:',
    CURRENT: 'Текущие',
    UPCOMING: 'Скоро',
    FUTURE: 'Будущие',
    PAST: 'Прошлые',
    SHOW_MAIN: 'Показать основные',
    HIDDEN: 'Скрытые',
    ADD_TENANT: 'Добавить Арендатора',
    RETURN_TO_MAIN: 'Вернуть в основные',
    HIDE_SELECTED: 'Скрыть выбранные',
    DELETE_SELECTED: 'Удалить выбранные',
    SELECT_ALL: 'Выбрать все',
    SELECT_ROW: 'Выбрать строку',
    TENANT_NAME: 'Имя Арендатора',
    APARTMENT_NUMBER: 'Квартира №',
    LOCATION: 'Расположение',
    STATUS: 'Статус',
    ENTRY_DATE: 'Дата Заезда',
    EXIT_DATE: 'Дата Выезда',
    RENT_PAYMENT: 'Платеж за аренду',
    UTILITY_PAYMENT: 'Платеж за счета',
    INTERNET_PAYMENT: 'Платеж за интернет',
    PAID: 'Оплачено',
    NOTES: 'Заметки',
    CREATED: 'Создано',
    ACTIONS: 'Действия',
    DELETE_RECORD: 'Удалить запись?',
    DELETE_DESCRIPTION: 'Действие необратимо. Запись будет удалена.',
    CANCEL: 'Отмена',
    DELETE: 'Удалить',
    DELETE_COLUMN: 'Удалить колонку',
    DELETE_COLUMN_CONFIRM: 'Удалить колонку?',
    DELETE_COLUMN_DESCRIPTION: 'Действие необратимо. Колонка будет удалена из всех записей.',
    ADD_COLUMN: 'Добавить колонку',
    SHOW_COLUMNS: 'Показать колонки',
  },
} as const;

export const DEBOUNCE_DELAY = 300;
export const MAX_RETRY_ATTEMPTS = 3;
