import { Property, Tenant } from "./schema";

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    apartmentNumber: 101,
    location: "Центральный район, 1 этаж",
    rooms: 2,
    readinessStatus: "FURNISHED",
    propertyType: "FOR_RENT",
    occupancyStatus: "OCCUPIED",
    urgentMatter: undefined,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prop-2",
    apartmentNumber: 102,
    location: "Центральный район, 1 этаж",
    rooms: 3,
    readinessStatus: "FURNISHED",
    propertyType: "FOR_RENT",
    occupancyStatus: "OCCUPIED",
    urgentMatter: "Протекает кран на кухне",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "prop-3",
    apartmentNumber: 201,
    location: "Центральный район, 2 этаж",
    rooms: 1,
    readinessStatus: "UNFURNISHED",
    propertyType: "FOR_SALE",
    occupancyStatus: "NOT_OCCUPIED",
    urgentMatter: undefined,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prop-4",
    apartmentNumber: 202,
    location: "Центральный район, 2 этаж",
    rooms: 4,
    readinessStatus: "FURNISHED",
    propertyType: "FOR_RENT",
    occupancyStatus: "OCCUPIED",
    urgentMatter: undefined,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prop-5",
    apartmentNumber: 301,
    location: "Центральный район, 3 этаж",
    rooms: 2,
    readinessStatus: "UNFURNISHED",
    propertyType: "FOR_SALE",
    occupancyStatus: "NOT_OCCUPIED",
    urgentMatter: "Сломан замок окна",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "prop-6",
    apartmentNumber: 302,
    location: "Центральный район, 3 этаж",
    rooms: 3,
    readinessStatus: "FURNISHED",
    propertyType: "FOR_RENT",
    occupancyStatus: "OCCUPIED",
    urgentMatter: undefined,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const mockTenants: Tenant[] = [
  {
    id: "tenant-1",
    name: "Иван Смирнов",
    apartmentId: "prop-1",
    entryDate: new Date("2024-01-20"),
    exitDate: undefined,
    notes: "Тихий арендатор, платит вовремя",
    status: "current",
    receivePaymentDate: new Date("2024-01-01"),
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "tenant-2",
    name: "Сара Иванова",
    apartmentId: "prop-2",
    entryDate: new Date("2024-01-25"),
    exitDate: undefined,
    notes: "Есть маленькая собака (одобрено)",
    status: "current",
    receivePaymentDate: new Date("2024-01-01"),
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "tenant-3",
    name: "Михаил Вильсон",
    apartmentId: "prop-4",
    entryDate: new Date("2024-02-01"),
    exitDate: undefined,
    notes: "Работает из дома, нужен стабильный интернет",
    status: "current",
    receivePaymentDate: new Date("2024-02-01"),
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "tenant-4",
    name: "Лиза Браун",
    apartmentId: "prop-6",
    entryDate: new Date("2024-02-10"),
    exitDate: undefined,
    notes: "Студентка, семестровая аренда",
    status: "current",
    receivePaymentDate: new Date("2024-02-01"),
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "tenant-5",
    name: "Алексей Петров",
    apartmentId: "prop-3",
    entryDate: new Date("2024-03-01"),
    exitDate: undefined,
    notes: "Новый арендатор, скоро заселяется",
    status: "future",
    receivePaymentDate: new Date("2024-03-01"),
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-02-25"),
  },
  {
    id: "tenant-6",
    name: "Мария Иванова",
    apartmentId: "prop-5",
    entryDate: new Date("2024-02-28"),
    exitDate: undefined,
    notes: "Заселяется на следующей неделе",
    status: "upcoming",
    receivePaymentDate: new Date("2024-03-01"),
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "tenant-7",
    name: "Владимир Соколов",
    apartmentId: "prop-1",
    entryDate: new Date("2023-06-01"),
    exitDate: new Date("2024-01-15"),
    notes: "Предыдущий арендатор, выехал",
    status: "past",
    receivePaymentDate: new Date("2024-01-01"),
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "tenant-8",
    name: "Елена Кузнецова",
    apartmentId: "prop-2",
    entryDate: new Date("2023-08-01"),
    exitDate: new Date("2024-01-20"),
    notes: "Предыдущий арендатор, договор аренды закончился",
    status: "past",
    receivePaymentDate: new Date("2024-01-01"),
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2024-01-20"),
  },
];
